var num = [8,3,7,5,2]
num.push(1)
num.sort()
console.log(num)
console.log(`O vetor tem ${num.length} posições!`)
console.log(`O primeiro valor do vetor é ${num[0]}`)
var x = num.indexOf(7)
var y = num.indexOf(2)
console.log(x)
console.log(y)